local RemoteNames = {
	RoundStateChanged = "RoundStateChanged",
	RoundTimerUpdated = "RoundTimerUpdated",
	
	RequestInteract = "RequestInteract",
	InteractionStateChanged = "InteractionStateChanged",
	RequestMovementState = "RequestMovementState",
	StatusEffectsChanged = "StatusEffectsChanged",
	RequestStruggleInput = "RequestStruggleInput",
	StruggleStateChanged = "StruggleStateChanged",
	RequestQTEInput = "RequestQTEInput",
	QTEStateChanged = "QTEStateChanged",
	RequestBreathHoldState = "RequestBreathHoldState",
	BreathHoldStateChanged = "BreathHoldStateChanged",
}

return RemoteNames
