local RemoteNames = {
	RoundStateChanged = "RoundStateChanged",
	RoundTimerUpdated = "RoundTimerUpdated",
	
	RequestInteract = "RequestInteract",
	InteractionStateChanged = "InteractionStateChanged",
	RequestMovementState = "RequestMovementState",
	StatusEffectsChanged = "StatusEffectsChanged",
	RequestStruggleInput = "RequestStruggleInput",
	StruggleStateChanged = "StruggleStateChanged",
	RequestQTEInput = "RequestQTEInput",
	QTEStateChanged = "QTEStateChanged",
	RequestBreathHoldState = "RequestBreathHoldState",
	BreathHoldStateChanged = "BreathHoldStateChanged",
	RequestPrimaryAttack = "RequestPrimaryAttack",
	RequestEquipWeapon = "RequestEquipWeapon",
	RequestUseInventoryItem = "RequestUseInventoryItem",
	CombatStateChanged = "CombatStateChanged",
	CombatHitConfirmed = "CombatHitConfirmed",
	StaminaStateChanged = "StaminaStateChanged",
	RequestRemnantAbility = "RequestRemnantAbility",
	RemnantStateChanged = "RemnantStateChanged",
	AuraRevealStateChanged = "AuraRevealStateChanged",
	RequestDevCommand = "RequestDevCommand",
	DevStateChanged = "DevStateChanged",
	DevPlacementStateChanged = "DevPlacementStateChanged",
}

return RemoteNames
