local ActionName = {
	Interact = "Interact",
	ToolboxUse = "ToolboxUse",
	SkillCheck = "SkillCheck",
	DoorSlam = "DoorSlam",

	Sprint = "Sprint",
	Crouch = "Crouch",
	Reload = "Reload",
	Flashlight = "Flashlight",

	Inventory = "Inventory",
	RadialMenu = "RadialMenu",

	Ability1 = "Ability1",
	Ability2 = "Ability2",
	Ability3 = "Ability3",

	PassiveAbility = "PassiveAbility",

	Perk1 = "Perk1",
	Perk2 = "Perk2",
	Perk3 = "Perk3",
	Perk4 = "Perk4",

	UseItem = "UseItem",
	Lockpick = "Lockpick",
}

return ActionName
