local ActionToken = {
	PrimaryContextAction = "PrimaryContextAction",
	SecondaryContextAction = "SecondaryContextAction",
	PrimaryFire = "PrimaryFire",

	Sprint = "Sprint",
	Crouch = "Crouch",
	Inventory = "Inventory",
	RadialMenu = "RadialMenu",
	Reload = "Reload",
	Flashlight = "Flashlight",

	Ability1 = "Ability1",
	Ability2 = "Ability2",
	Ability3 = "Ability3",

	Perk1 = "Perk1",
	Perk2 = "Perk2",
	Perk3 = "Perk3",
	Perk4 = "Perk4",
}

return ActionToken
